export const assets = [
  {
    id: 'AST-001',
    name: 'MRI Scanner',
    model: 'Magnetom Vida',
    manufacturer: 'Siemens Healthineers',
    serialNumber: 'SN-8839201',
    department: 'Radiology',
    location: 'Room 101',
    status: 'Active',
    purchaseDate: '2023-01-15',
    nextPmDate: '2024-07-15',
    value: 12000000,
    image: '/assets/mri.png'
  },
  {
    id: 'AST-002',
    name: 'Ventilator',
    model: 'Servo-u',
    manufacturer: 'Getinge',
    serialNumber: 'SN-4421002',
    department: 'ICU',
    location: 'Bed 4',
    status: 'Maintenance',
    purchaseDate: '2022-05-20',
    nextPmDate: '2024-05-20',
    value: 1500000,
    image: '/assets/ventilator.png'
  },
  {
    id: 'AST-003',
    name: 'Defibrillator',
    model: 'Lifepak 20e',
    manufacturer: 'Stryker',
    serialNumber: 'SN-1102938',
    department: 'Emergency',
    location: 'Trauma Bay 1',
    status: 'Active',
    purchaseDate: '2021-11-10',
    nextPmDate: '2024-11-10',
    value: 450000,
    image: '/assets/defib.png'
  },
  {
    id: 'AST-004',
    name: 'Infusion Pump',
    model: 'Infusomat Space',
    manufacturer: 'B. Braun',
    serialNumber: 'SN-5592011',
    department: 'Pediatrics',
    location: 'Ward 3',
    status: 'Active',
    purchaseDate: '2023-03-01',
    nextPmDate: '2024-09-01',
    value: 85000,
    image: '/assets/pump.png'
  },
  {
    id: 'AST-005',
    name: 'X-Ray Machine',
    model: 'MobileDaRt Evolution',
    manufacturer: 'Shimadzu',
    serialNumber: 'SN-7738291',
    department: 'Radiology',
    location: 'Room 104',
    status: 'Breakdown',
    purchaseDate: '2020-08-15',
    nextPmDate: '2024-08-15',
    value: 3500000,
    image: '/assets/xray.png'
  },
  {
    id: 'AST-006',
    name: 'Anesthesia Machine',
    model: 'Fabius GS premium',
    manufacturer: 'Dräger',
    serialNumber: 'SN-2291003',
    department: 'OT',
    location: 'OT 2',
    status: 'Active',
    purchaseDate: '2022-12-05',
    nextPmDate: '2024-06-05',
    value: 2800000,
    image: '/assets/anesthesia.png'
  },
  {
    id: 'AST-007',
    name: 'Patient Monitor',
    model: 'IntelliVue MX450',
    manufacturer: 'Philips',
    serialNumber: 'SN-9928102',
    department: 'ICU',
    location: 'Bed 2',
    status: 'Active',
    purchaseDate: '2023-06-20',
    nextPmDate: '2024-12-20',
    value: 320000,
    image: '/assets/monitor.png'
  },
  {
    id: 'AST-008',
    name: 'Ultrasound System',
    model: 'Voluson E10',
    manufacturer: 'GE Healthcare',
    serialNumber: 'SN-3382910',
    department: 'Obstetrics',
    location: 'Room 202',
    status: 'Active',
    purchaseDate: '2021-04-10',
    nextPmDate: '2024-10-10',
    value: 4200000,
    image: '/assets/ultrasound.png'
  }
];
